services:
  mysql:
    image: mysql:8.3
    container_name: ad_analytics_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql

  mongodb:
    image: mongo:7.0
    container_name: ad_analytics_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  cassandra:
    image: cassandra:4.1
    container_name: ad_analytics_cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra_data:/var/lib/cassandra
      - ./etl/cassandra_data:/app
    environment:
      - CASSANDRA_CLUSTER_NAME=AdAnalyticsCluster
      - CASSANDRA_NUM_TOKENS=16
    networks:
      - default

  etl:
    build: ./etl
    depends_on:
      - mysql
    profiles: ["etl"]
    volumes:
      - ./etl/data:/data

  analytics:
    build: ./etl
    depends_on:
      - mysql
    profiles: ["analytics"]
    command: python /app/analytics/run_reports.py
    volumes:
      - ./:/app

  mongo_loader:
    build: ./etl
    command: python /app/mongo_data/load_to_mongo.py
    depends_on:
      - mongodb
    profiles: ["mongo_loader"]
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    volumes:
      - ./etl/data:/data
      - ./etl:/app

  mongo_analytics:
    build: ./etl
    command: python /app/mongo_data/run_queries.py
    depends_on:
      - mongodb
    profiles: ["mongo_analytics"]
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    volumes:
      - ./etl/data:/data
      - ./etl:/app
      - ./etl/mongo_data/results:/app/results

  cassandra_loader:
    build: ./etl
    command: python /app/cassandra_data/load_to_cassandra.py
    depends_on:
      - cassandra
    profiles: ["cassandra_loader"]
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - CASSANDRA_HOST=${CASSANDRA_HOST}
      - CASSANDRA_PORT=${CASSANDRA_PORT}
      - CASSANDRA_USERNAME=${CASSANDRA_USERNAME}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
    volumes:
      - ./etl:/app
      - ./etl/data:/data

  cassandra_analytics:
    build: ./etl
    command: python /app/cassandra_data/run_queries.py
    depends_on:
      - cassandra
    profiles: ["cassandra_analytics"]
    environment:
      - CASSANDRA_HOST=${CASSANDRA_HOST}
      - CASSANDRA_PORT=${CASSANDRA_PORT}
      - CASSANDRA_USERNAME=${CASSANDRA_USERNAME}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
    volumes:
      - ./etl:/app
      - ./etl/data:/data
      - ./etl/cassandra_data/results:/app/results


